# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9ae24571acee40f9124131aaa21b8584"
name = "ACHTy AI - AI Recommends You"
application_url = "https://achty-shopify.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "achty-dev.myshopify.com"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_content,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://achty-shopify.vercel.app/auth/callback"
]

[pos]
embedded = false
